name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.0'
      
      - name: Build APK
        run: gradle assembleRelease
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: NotifAPI
          path: app/build/outputs/apk/
